### ISSUE TITLE
Irritating Informations 

### ISSUE THREAD

**Issue by ByteFax** [bigtreetech/PandaPWR#1]
in the shop there is a picture that shows that the adapter had a "rated load current" of 9A 
(a very high rate for cable that is used)
![Screenshot 2024-09-05 192212](https://github.com/user-attachments/assets/4b4af69e-dc01-4dcb-886d-58656f3dac9d)

the manual here show the same picture but only with 3A 

that is very irritating

**Comment by BTTJUSTIN** [comment]
Thanks for reporting. We will look into it check if the relative file need to be updated.
