### ISSUE TITLE
[Feature] Home Assistant Integration for Panda PWR

### ISSUE THREAD

**Issue by juanillo62gm** [bigtreetech/PandaPWR#14]
I’m excited to announce that I’ve developed a custom integration to connect the Panda PWR device with Home Assistant, enabling seamless control and monitoring directly within the platform.

I’ve recently acquired the Panda PWR device and have been thoroughly impressed with its capabilities. This project is still a work in progress, and I’m actively working to ensure it becomes 100% compatible with all the device’s features.

Your feedback and suggestions are welcome to help improve the integration and make it even more robust for the community!

https://github.com/juanillo62gm/HA-Panda-PWR

![Captura de pantalla 2024-11-18 a las 3 17 43](https://github.com/user-attachments/assets/95424eb6-8166-459c-9b4a-5d2f87647806)
![Captura de pantalla 2024-11-18 a las 3 17 53](https://github.com/user-attachments/assets/56f2e3c4-52c9-4df7-8e75-9d6bb90d65f1)
![Captura de pantalla 2024-11-18 a las 3 18 09](https://github.com/user-attachments/assets/52bc42a7-7ba7-40aa-8247-8e3358635831)

**Comment by dilixi** [comment]
> I’m excited to announce that I’ve developed a custom integration to connect the Panda PWR device with Home Assistant, enabling seamless control and monitoring directly within the platform.
> 
> I’ve recently acquired the Panda PWR device and have been thoroughly impressed with its capabilities. This project is still a work in progress, and I’m actively working to ensure it becomes 100% compatible with all the device’s features.
> 
> Your feedback and suggestions are welcome to help improve the integration and make it even more robust for the community!
> 
> https://github.com/juanillo62gm/HA-Panda-PWR
> 
> ![Captura de pantalla 2024-11-18 a las 3 17 43](https://private-user-images.githubusercontent.com/12599130/387032325-95424eb6-8166-459c-9b4a-5d2f87647806.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4OTkwNDcsIm5iZiI6MTczMTg5ODc0NywicGF0aCI6Ii8xMjU5OTEzMC8zODcwMzIzMjUtOTU0MjRlYjYtODE2Ni00NTljLTliNGEtNWQyZjg3NjQ3ODA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDAyNTkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMDg4M2U4NGI1MTQyN2Q4MjBiZjIyNWRiMWU2Mjg2MmYxNjJjYzY3MjY3Y2VmNzJlYmExNDE3ODQxN2ZlYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NnWudCw2aeGHA_qquVPYi3afGCGRRFs1NyUcuLw5QP0) ![Captura de pantalla 2024-11-18 a las 3 17 53](https://private-user-images.githubusercontent.com/12599130/387032330-56f2e3c4-52c9-4df7-8e75-9d6bb90d65f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4OTkwNDcsIm5iZiI6MTczMTg5ODc0NywicGF0aCI6Ii8xMjU5OTEzMC8zODcwMzIzMzAtNTZmMmUzYzQtNTJjOS00ZGY3LThlNzUtOWQ2YmI5MGQ2NWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDAyNTkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4OWE1NTcyNDdjYmJmYTc3ZDU3OGQwYmZiOTY5MGU5MDU0ZWNkZDIzZjRjYmE2NDc1ZmYwNzk4YWVlZGYwZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r3Z-tGPac38aJUFelG4ngbMbFB5SWn3cZClgbqJYU94) ![Captura de pantalla 2024-11-18 a las 3 18 09](https://private-user-images.githubusercontent.com/12599130/387032332-52bc42a7-7ba7-40aa-8247-8e3358635831.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4OTkwNDcsIm5iZiI6MTczMTg5ODc0NywicGF0aCI6Ii8xMjU5OTEzMC8zODcwMzIzMzItNTJiYzQyYTctN2JhNy00MGFhLTgyNDctOGUzMzU4NjM1ODMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDAyNTkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0Y2ExZThlYWUyNDY3OWJkZjcyYTAwZTE0OGRjYmVkZTViNjA0YmVkOTkxNzQzMTEyYzdkOTljNzc0MGVmMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.17oOL0smhrhk0n2s3pzWsdPOZIwaDC0loKRtpAeFga8)

That's great.
Do you mind if I add you to this repository?
You can add all of HA-Panda-PWR or just add a link to your repository.

**Comment by juanillo62gm** [comment]
That sounds great! I would really appreciate it if you could add a link to my repository in the README. It would be really helpful to easily access the integration.

This would also make it much easier to submit new releases to HACS, as it would automatically update the extension whenever I launch a new release. That's why I maintain the repository independently, so updates can be reflected directly in HACS.

**Comment by dilixi** [comment]
> That sounds great! I would really appreciate it if you could add a link to my repository in the README. It would be really helpful to easily access the integration.
> 
> This would also make it much easier to submit new releases to HACS, as it would automatically update the extension whenever I launch a new release. That's why I maintain the repository independently, so updates can be reflected directly in HACS.

Done.
