### ISSUE TITLE
Can't bind with Panda Touch

### ISSUE THREAD

**Issue by Knud3** [bigtreetech/PandaPWR#5]
I do not get any message to Panda Touch when I enter PWR in bind mode (pressing bind button for 3 seconds).

When I did reset both Panda Touch and PWR (pressing bind button for 8 seconds), I once did get that message, but after pressing `confirm` it did not do anything.

I tried reseting several times, but I only get message once after every reset and it wont do anything even after confirming.

And yes, I did tried to hold Touch on every possible angle on PWR when binding.

I have also tried to do `First Connection` setup with my WiFi, and I can use PWR in standalone mode without issues.

Touch is using `v1.0.5` firmware.

What can be done?

**Comment by Rowan2233** [comment]
hey bro, i think you could press and hold the side button for about 8 seconds until the red light flashes and turns blue to restore Panda PWR to factory settings, then rebind Panda PWR.

**Comment by dilixi** [comment]
> I do not get any message to Panda Touch when I enter PWR in bind mode.
> 
> When I did reset both Panda Touch and PWR, I once did get that message, but after pressing `confirm` it did not do anything.
> 
> I tried reseting several times, but I only get message once after every reset and it wont do anything even confirming.
> 
> And yes, I did tried to hold Touch on every possible angle on PWR when binding.
> 
> What can be done?
Please place PandaTouch on the outer shell of the Panda pressurized water reactor. When attempting to bind Panda Touch and Panda PWR, they should be placed very close together.
Can you upload a video that displays everything?

**Comment by dilixi** [comment]
> I do not get any message to Panda Touch when I enter PWR in bind mode.
> 
> When I did reset both Panda Touch and PWR, I once did get that message, but after pressing `confirm` it did not do anything.
> 
> I tried reseting several times, but I only get message once after every reset and it wont do anything even confirming.
> 
> And yes, I did tried to hold Touch on every possible angle on PWR when binding.
> 
> What can be done?

Please place PandaTouch on the outer shell of the Panda pressurized water reactor. When attempting to bind Panda Touch and Panda PWR, they should be placed very close together.
Can you upload a video that displays everything?

**Comment by bigtreetech** [comment]
> > I do not get any message to Panda Touch when I enter PWR in bind mode.
> > When I did reset both Panda Touch and PWR, I once did get that message, but after pressing `confirm` it did not do anything.
> > I tried reseting several times, but I only get message once after every reset and it wont do anything even confirming.
> > And yes, I did tried to hold Touch on every possible angle on PWR when binding.
> > What can be done?
> 
> Please place PandaTouch on the outer shell of the Panda pressurized water reactor. When attempting to bind Panda Touch and Panda PWR, they should be placed very close together. Can you upload a video that displays everything?

He has already mentioned that he tried to hold it very close.

![image](https://github.com/user-attachments/assets/8e7d9e2a-2003-4ada-9904-3c6b2e8ddbad)

**Comment by dilixi** [comment]
> I do not get any message to Panda Touch when I enter PWR in bind mode.
> 
> When I did reset both Panda Touch and PWR, I once did get that message, but after pressing `confirm` it did not do anything.
> 
> I tried reseting several times, but I only get message once after every reset and it wont do anything even confirming.
> 
> And yes, I did tried to hold Touch on every possible angle on PWR when binding.
> 
> What can be done?

Ca

> > > I do not get any message to Panda Touch when I enter PWR in bind mode.
> > > When I did reset both Panda Touch and PWR, I once did get that message, but after pressing `confirm` it did not do anything.
> > > I tried reseting several times, but I only get message once after every reset and it wont do anything even confirming.
> > > And yes, I did tried to hold Touch on every possible angle on PWR when binding.
> > > What can be done?
> > 
> > 
> > Please place PandaTouch on the outer shell of the Panda PWR. When attempting to bind Panda Touch and Panda PWR, they should be placed very close together. Can you upload a video that displays everything?
> 
> He has already mentioned that he tried to hold it very close.
> 
> ![image](https://private-user-images.githubusercontent.com/38851044/369360320-8e7d9e2a-2003-4ada-9904-3c6b2e8ddbad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4Mjg4MTYsIm5iZiI6MTcyNjgyODUxNiwicGF0aCI6Ii8zODg1MTA0NC8zNjkzNjAzMjAtOGU3ZDllMmEtMjAwMy00YWRhLTk5MDQtM2M2YjJlOGRkYmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDEwMzUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhZDgyMDQ1ZjVkN2JjZTlmYjI1MjM5NjQxYzAyYWQ3MDg2MmZmM2IxZWUwODc4MGE4ZTIzNWIzNmVkMmJiNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._Sx-sAKLVJfVC_fykU2Eyn5GO6Ww34ZD0OApoq3EgNc)

Thank you,you are right.

**Comment by dilixi** [comment]
> I do not get any message to Panda Touch when I enter PWR in bind mode.
> 
> When I did reset both Panda Touch and PWR, I once did get that message, but after pressing `confirm` it did not do anything.
> 
> I tried reseting several times, but I only get message once after every reset and it wont do anything even confirming.
> 
> And yes, I did tried to hold Touch on every possible angle on PWR when binding.
> 
> What can be done?

Can you upload a shotscreen about the Firmware version of Panda Touch.

![image](https://github.com/user-attachments/assets/9d552076-398d-4866-9da3-de0d2fc19136)

**Comment by Knud3** [comment]
> hey bro, i think you could press and hold the side button for about 8 seconds until the red light flashes and turns blue to restore Panda PWR to factory settings, then rebind Panda PWR.

As said, I have tried reseting several times.

> Did you release the button after Hold it for 3s.

Yes. Even tho your support personel instructed `Press and hold for eight seconds to connect.`

I have replied with video demonstration to your support email.

**Comment by dilixi** [comment]
> > hey bro, i think you could press and hold the side button for about 8 seconds until the red light flashes and turns blue to restore Panda PWR to factory settings, then rebind Panda PWR.
> 
> As said, I have tried reseting several times.
> 
> > Did you release the button after Hold it for 3s.
> 
> Yes. Even tho your support personel instructed `Press and hold for eight seconds to connect.`
> 
> I have replied with video demonstration to your support email.

Don't worry.
Could you mind uploadind the video by github?
or send it to this email(1284513393@qq.com).

**Comment by Kaji-fi** [comment]
I have same problem. I have tried to pair it with Panda Touch with no luck. Rarely popup appears and when I push "confirm" nothing happens.

**Comment by dilixi** [comment]
> I have same problem. I have tried to pair it with Panda Touch with no luck. Rarely popup appears and when I push "confirm" nothing happens.

Hi, I have send a email to you, please check it out first.
Thank you.

**Comment by Kaji-fi** [comment]
> > I have same problem. I have tried to pair it with Panda Touch with no luck. Rarely popup appears and when I push "confirm" nothing happens.
> 
> Hi, I have send a email to you, please check it out first. Thank you.

Pairing worked after upgrading it to v1.0.1.

**Comment by dilixi** [comment]
We have found a solution to this problem.
