### ISSUE TITLE
FR: Make PWR to bind Touch when using `LAN Only mode`

### ISSUE THREAD

**Issue by Knud3** [bigtreetech/PandaPWR#6]
This is follow up to #5.

After messaging your support I have got very mixed instructions, but after all it seems that my issue is that I use `LAN Only mode` with my printer. Also, I do not want to login to Touch either.

Your support is saying that `You need to log in to your account before you can connect to wifi`. How it is even possible to login cloud account **before** internet is even connected?

I have read instructions on wiki page and PWR repository PDF carefully. I do not find any mentions about login to Bambu Lab account is mandatory.

In marketing material and instruction pages do not have any mentions that PWR do not work in `LAN Only mode`.

This feature is must, and you are missleading customers to not to mention about it in marketing material.

**Comment by dilixi** [comment]
> This is follow up to #5.
> 
> After messaging your support I have got very mixed instructions, but after all it seems that my issue is that I use `LAN Only mode` with my printer. Also, I do not want to login to Touch either.
> 
> Your support is saying that `You need to log in to your account before you can connect to wifi`. How it is even possible to login cloud account **before** internet is even connected?
> 
> I have read instructions on wiki page and PWR repository PDF carefully. I do not find any mentions about login to Bambu Lab account is mandatory.
> 
> In marketing material and instruction pages do not have any mentions that PWR do not work in `LAN Only mode`.
> 
> This feature is must, and you are missleading customers to not to mention about it in marketing material.

Hi Knud3,I will try my best to solve this problem.
Please don't worry.
Maybe we missed something.
Let me watch the video first. Please send it to me（ 1284513393@qq.com )

**Comment by Knud3** [comment]
I did send you the video. Its 25mb attachement, so I hope it come through. Thanks!

**Comment by dilixi** [comment]
> I did send you the video. Its 25mb attachement, so I hope it come through. Thanks!
I didi send you a video to you email also.
Does it works when you copy my operation from the video?And please send me the shotscreen of the pandatouch's firmware version. thank you.

**Comment by dilixi** [comment]
This is related to the nvs flash of ESP idf.
