### ISSUE TITLE
Please provide informations about the /get_power endpoint

### ISSUE THREAD

**Issue by capull0** [bigtreetech/PandaPWR#8]
I had an ESP32-C2 around here and was able to flash the PWR firmware to it.
I found the pair-pin and i was able to pair this esp32 with my Panda Touch.
Unfortunately i don't own a Panda PWR, so i don't know how the esp32 is reading the power values (SPI, i2c?)

My goal was to show already existing power values from my Homeassistant/MQTT and at the panda touch.
I found out, that the Panda Touch is polling /get_power from the PWR every second.

Would be very nice to provide the data structure of /get_power and how the 2 bytes checksum is calculated.
If you don't want to give us such informations, please remove the PWR informations from Panda Touch screen, it uses half of the home-screen, if no PWR is connected.

Would be also very useful to have the possibility to add a virtual PWR to the Panda touch and communicate over a simple API to send/receive metrics/commands.

**Comment by dilixi** [comment]
> I had an ESP32-C2 around here and was able to flash the PWR firmware to it. I found the pair-pin and i was able to pair this esp32 with my Panda Touch. Unfortunately i don't own a Panda PWR, so i don't know how the esp32 is reading the power values (SPI, i2c?)
> 
> My goal was to show already existing power values from my Homeassistant/MQTT and at the panda touch. I found out, that the Panda Touch is polling /get_power from the PWR every second.
> 
> Would be very nice to provide the data structure of /get_power and how the 2 bytes checksum is calculated. If you don't want to give us such informations, please remove the PWR informations from Panda Touch screen, it uses half of the home-screen, if no PWR is connected.
> 
> Would be also very useful to have the possibility to add a virtual PWR to the Panda touch and communicate over a simple API to send/receive metrics/commands.

Hi,please send a email to me,1284513393@qq.com.

**Comment by dilixi** [comment]
> I had an ESP32-C2 around here and was able to flash the PWR firmware to it. I found the pair-pin and i was able to pair this esp32 with my Panda Touch. Unfortunately i don't own a Panda PWR, so i don't know how the esp32 is reading the power values (SPI, i2c?)
> 
> My goal was to show already existing power values from my Homeassistant/MQTT and at the panda touch. I found out, that the Panda Touch is polling /get_power from the PWR every second.
> 
> Would be very nice to provide the data structure of /get_power and how the 2 bytes checksum is calculated. If you don't want to give us such informations, please remove the PWR informations from Panda Touch screen, it uses half of the home-screen, if no PWR is connected.
> 
> Would be also very useful to have the possibility to add a virtual PWR to the Panda touch and communicate over a simple API to send/receive metrics/commands.
Hi ,
you can check it out by this link.

https://github.com/bigtreetech/PandaPWR/blob/master/pwr_api.md#get-http19216841get_power
